print("Dragan Arina")
print("28.06.2004")
print("Molodoveanca")
print("Necasatorita")
print("Institutia Publica Liceul Teoretic M.Eminescu")
print("limba engleza limba germana")
print("069850142")
print("draganarina7@gmail.com")
print("str.Dcebal 121a")
print("romane detective nuvele")